### PR TITLE
Rangefinder fix

### PR DESCRIPTION
**Pull request by togfoxy**
PR order:

- asset loader
- enet
- rangefinder fix

### CODE REVIEW

**Comment by Philbywhizz** [comment]
I'd wait for #194 before merging this in as there could be some changes required with the refactoring of enum.lua and drawobjects.lua

**Comment by togfoxy** [comment]
Yup. It even comes after enet.

**Review by MadByteDE — COMMENTED** [review]
this will need to be re-implemented almost entirely after PR #194 has been resolved.
Also I thing this is more of a workaround then a solution. We should look for alternative approaches that don't just hard limit the distance we create the terrain and objects but instead just need to calculate the next position, even before any object has been created by using deterministic functions to  calculate the locations for each base object.
That wouldn't just solve the rangefinder issue but also allow us to not pregenerate anything that is outside the visible range of the player, which would mean a huge performance and memory efficiency boost.

**Comment by togfoxy** [comment]
Going to close this PR and rewrite the fix later.

**Pull request closed without merging**
