### PR TITLE
Returned buildings back to the terrain generation algorithm

### LINKED ISSUE #178: Return the creation/drawing of building objects to the code. See comments.
During the refactoring of the terrain and bases to be 'on demand', the generation of buildings was removed and needs to be put back in again.

### PR DESCRIPTION
**Pull request by togfoxy**
Fixes #178

### CODE REVIEW

**Comment by togfoxy** [comment]
Please play test if you have a chance.

**Comment by MadByteDE** [comment]
### 1. Buildings spawning on top of fuel bases
Needs a check to make sure there is no fuel station at the same location

### 2. Buildings sometimes spawn in view of the player
Might be an issue with `love.math.random(200,2000)`. 200 might not be enough to let them spawn outside of the players field of view? Needs testing.

### 3. Old buildings should be removed
Same as for the terrain. Doesn't need to be fixed for this PR I guess :wink: 

Just as an note: I haven't looked at the code too much.

**Comment by togfoxy** [comment]
I'm okay with 1 and 3 but 2 happened just the one time and couldn't be replicated. I'll dig deeper.

**Comment by MadByteDE** [comment]
I had it at least 3-4 times, especially while flying a bit faster.

**Comment by togfoxy** [comment]
Hope someone can have a quick playtest on this one. It's not 100% fixed but fixed enough.

**Comment by MadByteDE** [comment]
Still sometimes get buildings on top of fuel bases but I don't see any buildings popping in anymore, so that's nice.

**Pull request merged**
