### PR TITLE
First iteration - Code organization into seperate files - Lander / Terrain code

### PR DESCRIPTION
**Pull request by MadByteDE**
As discussed previously I'd like to get the code organized more into separate files to better find relevant code i.e when adding features or changing existing code and to keep a better overview. 

I know @Philbywhizz is already working on something similar, this is just meant to be a suggestion as first iteration for code reorganization for the meantime, until we decided how everything ultimately should be structured.

Main changes in this PR are terrain / lander functions moved from main.lua and functions.lua into their own files. 

I had to make minor changes to the code, e.g changing function arguments called "Lander" to "landerObj" to avoid having arguments referring to the global Lander table instead of the lander objects ("garrLanders[1]").

### CODE REVIEW

**Comment by MadByteDE** [comment]
Noticed there was a commit while I wrote the PR - I'll look into the changes and add them to the changes I made with the restruct code.

**Comment by togfoxy** [comment]
Happy for you to do what you're doing but note that I 'parameterised' the functions in main.lua and merged them into the main branch.

Super simple to repeat again if necessary.

**Comment by Philbywhizz** [comment]
I had already started separating out the lander code, but you have beaten me too it (so your code wins). I like the way it is structured.

**Comment by togfoxy** [comment]
I like this. Nice work.

This PR is still draft for review. I have reviewed but not tested it. If you would like to merge to 'main' and you have access then please do so. :)

**Review by Philbywhizz — COMMENTED** [review]
Looks good! - I'd like to have a test of the changes before merging into main, its a fairly significant refactor.

**Comment by MadByteDE** [comment]
> I had already started separating out the lander code, but you have beaten me too it (so your code wins). I like the way it is structured.

Thanks, I hope everyone can work with that. Feel free to add/change/remove whatever you see fit :smile:



> Looks good! - I'd like to have a test of the changes before merging into main, its a fairly significant refactor.

I'll open it for review now.

**Comment by MadByteDE** [comment]
I have to admit, I've never resolved merge conflicts until now, If there's an issue with the merge then it boils down to this fact. I tested the changes previously and everything worked fine.

**Comment by MadByteDE** [comment]
Just realized you said  you want to review changes before merge *facepalm* Please revert if needed. Still getting used to git & github.

**Comment by togfoxy** [comment]
I'm sure we can iron out any problems. :)

**Comment by Philbywhizz** [comment]
Don't stress to much about the PRs - that's the beauty of git, everything can be undone and rewound back.

**Pull request merged**
