### PR TITLE
Enet v2

### PR DESCRIPTION
**Pull request by togfoxy**
To be merged after the Pause PR.

### CODE REVIEW

**Comment by Philbywhizz** [comment]
I'm getting this error when I get a client to join

Error: objects/terrain.lua:141: attempt to perform arithmetic on global 'gintWorldOffset' (a nil value)

**Comment by togfoxy** [comment]
Sorry - I did a merge before it was due and then I did a non-merge. Try again. I'll also investigate.

**Comment by togfoxy** [comment]
I get error too. Let me check.

**Comment by togfoxy** [comment]
IDK. Creating a new PR.

**Pull request closed without merging**
