### PR TITLE
Fix menu ip/port inputs

### PR DESCRIPTION
**Pull request by Philbywhizz**
The IP and ports weren't populating correctly on the main menu. This PR fixs it.

### CODE REVIEW

**Comment by togfoxy** [comment]
Curious if anyone has tried multiplayer over LAN or even internet? I have tested two clients on same computer but not two different computers. (can connect to 'localhost' for debugging)

**Comment by Philbywhizz** [comment]
I've only done it on a single computer myself. Should work in theory. Actually let me test that our right now

**Comment by Philbywhizz** [comment]
Sadly I couldn't get it to work on my local LAN.

**Comment by togfoxy** [comment]
Okay. Good to know. I'm making up the entire socket code as I go. Good learning experience.

**Pull request merged**
